sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest-v10.x/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  - echo $NODE_VERSION
#  - sudo curl -sSL https://get.docker.com/ | sh
  - docker version
  - docker info
#  - sudo rm /usr/local/bin/docker-compose
#  - export DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - docker version
#  - docker-compose version

script:
  - export IMAGE=$TRAVIS_REPO_SLUG:$NODE_VERSION
  - docker pull $IMAGE || echo 'image not found'
  - |
    if [[ "$(docker images -q $IMAGE 2> /dev/null)" == "" ]]; then
      docker build -t $IMAGE -t $TRAVIS_REPO_SLUG:latest --build-arg NODE_VERSION=$NODE_VERSION .
      docker images
      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      docker push $TRAVIS_REPO_SLUG
    fi
