sudo: required

notifications:
  email:
    on_success: never
    on_failure: change


before_install:
  - export LATEST_VERSION=$(wget -qO- https://nodejs.org/dist/latest-v8.x/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  - echo $LATEST_VERSION
  - export NODE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  - echo $NODE_VERSION

install:
  - sudo curl -sSL https://get.docker.com/ | sh
#  - sudo rm /usr/local/bin/docker-compose
#  - export DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - docker version
#  - docker-compose version

script:
  - docker version
  - docker info

after_success:
  - export REPO=$TRAVIS_REPO_SLUG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG --build-arg NODE_VERSION=$NODE_VERSION .
  - docker images
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - docker push $REPO
